server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db.migration.v1/changelog.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: dancestudio
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  servlet:
    multipart:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 129877534425-6qk9a3sms10kicovojosigkjdagkomob.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
logging:
  level:
    org.springframework.web: DEBUG