server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db.migration.v1/changelog.yaml
