server:
  port: ${PORT:8080}
  servlet:
    context-path: /
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/postgres}
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db.migration.v1/changelog.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: dancestudio
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  servlet:
    multipart:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant-path-matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: ekaterina.selivanova.work@gmail.com
    password: pnfovgfnbdmfugtu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.springframework.web: DEBUG